# Generated by Django 4.2.4 on 2024-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_login_admin_name_alter_admin_email_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
