# Generated by Django 4.2.4 on 2024-12-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_cardsupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='cardsupload',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cardsupload',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
