# Generated by Django 4.2.4 on 2024-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-11 12:00:00'),
            preserve_default=False,
        ),
    ]
